import "../reel-studio.css";
import { useEffect } from "react";
import Autoposter from "./autoposter";
import ReelComposer from "../components/reel-composer-v2";
import ReelStudioV1 from "../components/reel-studio-v1";

type BrandName = "Zawaago" | "InnoTech";
const LOGOS: Record<BrandName, string> = { Zawaago: "/brand/zawaago-logo-final.svg", InnoTech: "/brand/innotech-logo-final.svg" };
type FetchLike = (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
function loadImage(blob: Blob){return new Promise<HTMLImageElement>((resolve,reject)=>{const url=URL.createObjectURL(blob);const image=new Image();image.onload=()=>{URL.revokeObjectURL(url);resolve(image)};image.onerror=()=>{URL.revokeObjectURL(url);reject(new Error("Could not decode image for branding."))};image.src=url;});}
async function applyBranding(imageUrl:string,pageName:BrandName,branding:string,logoPosition:string,fetcher:FetchLike){if(branding==="No branding")return imageUrl;const [ir,lr]=await Promise.all([fetcher(imageUrl,{cache:"no-store"}),fetcher(LOGOS[pageName],{cache:"force-cache"})]);if(!ir.ok||!lr.ok)throw new Error("Branding assets could not be loaded.");const [ib,lb]=await Promise.all([ir.blob(),lr.blob()]);const [image,logo]=await Promise.all([loadImage(ib),loadImage(lb)]);const canvas=document.createElement("canvas");canvas.width=image.naturalWidth||image.width;canvas.height=image.naturalHeight||image.height;const ctx=canvas.getContext("2d");if(!ctx)throw new Error("Browser canvas is unavailable for logo composition.");ctx.drawImage(image,0,0,canvas.width,canvas.height);const min=Math.min(canvas.width,canvas.height),target=min*(branding==="Branded creative"?.20:.14),scale=target/Math.max(logo.naturalWidth||logo.width,logo.naturalHeight||logo.height),lw=(logo.naturalWidth||logo.width)*scale,lh=(logo.naturalHeight||logo.height)*scale,margin=Math.max(24,Math.round(min*.04));let x=margin,y=margin;if(logoPosition==="Top Right")x=canvas.width-lw-margin;if(logoPosition==="Bottom Left")y=canvas.height-lh-margin;if(logoPosition==="Bottom Right"){x=canvas.width-lw-margin;y=canvas.height-lh-margin;}ctx.save();ctx.globalAlpha=branding==="Branded creative"?.98:.92;ctx.shadowColor="rgba(0,0,0,.22)";ctx.shadowBlur=Math.max(6,Math.round(min*.008));ctx.shadowOffsetY=Math.max(2,Math.round(min*.003));ctx.drawImage(logo,x,y,lw,lh);ctx.restore();const output=await new Promise<Blob|null>(r=>canvas.toBlob(r,"image/jpeg",.92));if(!output)throw new Error("Could not encode the branded image.");const form=new FormData();form.append("pageName",pageName);form.append("file",output,`${pageName.toLowerCase()}-branded.jpg`);const upload=await fetcher("/api/autoposter/assets/brand",{method:"POST",body:form});const data:any=await upload.json().catch(()=>({}));if(!upload.ok||!data.imageUrl)throw new Error(data.details||data.error||"Could not store the branded image.");return data.imageUrl as string;}
export default function BrandedAutoposter(){useEffect(()=>{const original=window.fetch.bind(window) as FetchLike;const wrapped:FetchLike=async(input,init)=>{const response=await original(input,init);const url=typeof input==="string"?input:input instanceof Request?input.url:input.toString();if(!url.endsWith("/api/autoposter/generate-image")||!response.ok)return response;const body=typeof init?.body==="string"?JSON.parse(init.body):null;const pageName:BrandName=body?.pageName==="InnoTech"?"InnoTech":"Zawaago";const branding=String(body?.branding||"Subtle watermark"),logoPosition=String(body?.logoPosition||"Bottom Right");if(branding==="No branding"){try{const data:any=await response.clone().json();const existing:any=JSON.parse(localStorage.getItem("autoposter:latest-creative")||"{}");localStorage.setItem("autoposter:latest-creative",JSON.stringify({...existing,pageName,topic:body?.topic||existing.topic||"",imageUrl:data?.imageUrl||"",imagePrompt:data?.prompt||existing.imagePrompt||body?.imgPrompt||""}));}catch{}return response;}try{const data:any=await response.clone().json();if(!data?.imageUrl)throw new Error("Generated visual did not return an image URL.");const branded=await applyBranding(data.imageUrl,pageName,branding,logoPosition,original);localStorage.setItem("autoposter:latest-creative",JSON.stringify({...JSON.parse(localStorage.getItem("autoposter:latest-creative")||"{}"),pageName,topic:body?.topic||"",imageUrl:branded,imagePrompt:data.prompt||body?.imgPrompt||""}));return new Response(JSON.stringify({...data,imageUrl:branded,source:`${data.source||"generated"}+real-logo-overlay`,brandingApplied:true}),{status:response.status,headers:{"Content-Type":"application/json"}});}catch(error){return new Response(JSON.stringify({error:"Branding failed",details:error instanceof Error?error.message:String(error)}),{status:502,headers:{"Content-Type":"application/json"}});}};window.fetch=wrapped;return()=>{window.fetch=original};},[]);return <><Autoposter/><ReelStudioV1/><ReelComposer/></>;}
