import { useMemo, useRef, useState } from "react";
import { ArrowLeft, CheckCircle, FilmStrip, Play, Sparkle, SpeakerHigh, WarningCircle } from "@phosphor-icons/react";

type Scene = { scene: number; durationSeconds: number; narration: string; caption: string; visualPrompt: string; imageUrl?: string };
type Storyboard = { title: string; hook: string; totalSeconds: number; scenes: Scene[]; pageName: string; language: string; audience: string };
type Branding = "none" | "Zawaago" | "InnoTech";
type DeviceProfile = { kind: "desktop" | "mobile" | "tablet"; mp4: string; width: number; height: number; fps: number; videoBitrate: number; chunkMs: number; note: string };

const LOGOS: Record<Exclude<Branding, "none">, string> = { Zawaago: "/brand/zawaago-logo-final.svg", InnoTech: "/brand/innotech-logo-final.svg" };
const MP4_TYPES = ["video/mp4;codecs=avc1.424028,mp4a.40.2", "video/mp4;codecs=avc1.4d401f,mp4a.40.2", "video/mp4"];

function detectDevice(): DeviceProfile {
  if (typeof navigator === "undefined") return { kind: "desktop", mp4: "", width: 1080, height: 1920, fps: 30, videoBitrate: 3500000, chunkMs: 500, note: "Desktop 1080×1920 profile." };
  const ua = navigator.userAgent.toLowerCase();
  const mobile = /android|iphone|ipod|mobile/.test(ua);
  const tablet = /ipad|tablet/.test(ua) || (navigator.maxTouchPoints > 1 && Math.min(screen.width, screen.height) >= 600);
  const mp4 = typeof MediaRecorder !== "undefined" ? MP4_TYPES.find((t) => MediaRecorder.isTypeSupported(t)) || "" : "";
  if (mobile && !tablet) return { kind: "mobile", mp4, width: 1080, height: 1920, fps: 30, videoBitrate: 2600000, chunkMs: 750, note: "Mobile-safe 1080×1920 profile with lower bitrate to reduce memory pressure." };
  if (tablet) return { kind: "tablet", mp4, width: 1080, height: 1920, fps: 30, videoBitrate: 3000000, chunkMs: 650, note: "Tablet-safe 1080×1920 profile." };
  return { kind: "desktop", mp4, width: 1080, height: 1920, fps: 30, videoBitrate: 3500000, chunkMs: 500, note: "Desktop 1080×1920 profile." };
}
function wrapText(ctx: CanvasRenderingContext2D, text: string, maxWidth: number) { const words = text.split(/\s+/); const lines: string[] = []; let line = ""; for (const word of words) { const next = line ? `${line} ${word}` : word; if (ctx.measureText(next).width > maxWidth && line) { lines.push(line); line = word; } else line = next; } if (line) lines.push(line); return lines; }
function drawCover(ctx: CanvasRenderingContext2D, image: HTMLImageElement, width: number, height: number, progress: number) { const ratio = image.naturalWidth / image.naturalHeight; const target = width / height; let sw = image.naturalWidth; let sh = image.naturalHeight; if (ratio > target) sw = sh * target; else sh = sw / target; const sx = (image.naturalWidth - sw) / 2; const sy = (image.naturalHeight - sh) / 2; const zoom = 1.035 + Math.sin(progress * Math.PI) * 0.03; const dw = width * zoom; const dh = height * zoom; ctx.drawImage(image, sx, sy, sw, sh, (width - dw) / 2, (height - dh) / 2, dw, dh); }
async function loadImage(src: string) { const image = new Image(); image.decoding = "async"; image.src = src; await image.decode(); return image; }
function drawBrandMark(ctx: CanvasRenderingContext2D, logo: HTMLImageElement, width: number) { const logoW = Math.round(width * 0.22); const logoH = logoW * (logo.naturalHeight / logo.naturalWidth); const pad = Math.max(8, Math.round(width * 0.018)); const badgeW = logoW + pad * 2; const badgeH = logoH + pad * 2; const x = width - badgeW - 22; const y = 22; ctx.save(); ctx.shadowColor = "rgba(0,0,0,.22)"; ctx.shadowBlur = 14; ctx.shadowOffsetY = 3; ctx.fillStyle = "rgba(255,255,255,.92)"; ctx.beginPath(); ctx.roundRect(x, y, badgeW, badgeH, Math.round(pad * 1.35)); ctx.fill(); ctx.restore(); ctx.drawImage(logo, x + pad, y + pad, logoW, logoH); }

export default function ReelLab() {
  const [prompt, setPrompt] = useState("Explain why AI agents are different from chatbots, in a practical way for business owners.");
  const [sourcePost, setSourcePost] = useState(""); const [sourceMode, setSourceMode] = useState<"prompt" | "post">("prompt");
  const [language, setLanguage] = useState("Hinglish"); const [branding, setBranding] = useState<Branding>("none");
  const [storyboard, setStoryboard] = useState<Storyboard | null>(null); const [device] = useState<DeviceProfile>(() => detectDevice());
  const [busy, setBusy] = useState<"storyboard" | "assets" | "render" | "save" | null>(null); const [status, setStatus] = useState(""); const [error, setError] = useState("");
  const [videoUrl, setVideoUrl] = useState(""); const [videoMime, setVideoMime] = useState(""); const [savedVideoUrl, setSavedVideoUrl] = useState(""); const canvasRef = useRef<HTMLCanvasElement>(null);
  const total = useMemo(() => storyboard?.scenes.reduce((sum, scene) => sum + scene.durationSeconds, 0) || 0, [storyboard]);
  const canRender = !!storyboard && storyboard.scenes.length === 5 && storyboard.scenes.every((scene) => !!scene.imageUrl);

  async function createStoryboard() {
    const topic = (sourceMode === "post" ? sourcePost : prompt).trim(); if (!topic) { setError(sourceMode === "post" ? "Paste a source post first." : "Enter a Reel prompt first."); return; }
    setBusy("storyboard"); setError(""); setVideoUrl(""); setSavedVideoUrl(""); setStatus("Designing a five-scene Reel story…");
    try { const response = await fetch("/api/reel-lab/storyboard", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ pageName: branding === "none" ? "Zawaago" : branding, language, topic, sourceCaption: sourceMode === "post" ? sourcePost : undefined, audience: "Business Owners and Professionals" }) }); const data: any = await response.json(); if (!response.ok) throw new Error(data.details || data.error || "Storyboard generation failed"); setStoryboard(data as Storyboard); setStatus("Storyboard ready. Generate the five scene visuals next."); } catch (e) { setError(e instanceof Error ? e.message : String(e)); } finally { setBusy(null); }
  }

  async function generateSceneAssets() {
    if (!storyboard) return; setBusy("assets"); setError(""); setVideoUrl(""); setSavedVideoUrl("");
    try { for (let i = 0; i < storyboard.scenes.length; i += 1) { const scene = storyboard.scenes[i]; setStatus(`Generating scene visual ${i + 1}/${storyboard.scenes.length}…`); const response = await fetch("/api/autoposter/generate-image", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ pageName: branding === "none" ? "Zawaago" : branding, topic: `${storyboard.title} · scene ${scene.scene}`, contentType: "Educational Reel Scene", tone: language === "Hinglish" ? "Professional Hinglish" : "Professional English", language, audience: "Business Owners and Professionals", visualStyle: "Premium Editorial Cinematic", aspectRatio: "Portrait 9:16", branding: "No branding", logoPosition: "Bottom Right", cta: "None", customPrompt: `${scene.visualPrompt} Clean artwork only. No text, logos, letters, numbers, subtitles or watermarks. Designed for a vertical 9:16 educational Reel.`, imgPrompt: scene.visualPrompt }) }); const data: any = await response.json(); if (!response.ok || !data.imageUrl) throw new Error(data.details || data.error || `Scene ${i + 1} image generation failed`); setStoryboard((current) => current ? { ...current, scenes: current.scenes.map((item) => item.scene === scene.scene ? { ...item, imageUrl: data.imageUrl } : item) } : current); } setStatus("All scene visuals are ready. Render the Reel next."); } catch (e) { setError(e instanceof Error ? e.message : String(e)); } finally { setBusy(null); }
  }

  async function renderReel() {
    if (!canRender) return; if (!device.mp4) { setError(`This ${device.kind} browser does not expose a supported MP4 MediaRecorder profile. Try the latest Chrome or Safari on a desktop/laptop.`); return; }
    setBusy("render"); setError(""); setVideoUrl(""); setSavedVideoUrl(""); setStatus(`Generating ${language} voice narration…`); let audioUrl = ""; let audioContext: AudioContext | null = null;
    try {
      const narration = storyboard.scenes.map((scene) => scene.narration).join(" "); const audioResponse = await fetch("/api/reel-lab/tts", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ text: narration, speaker: "shubh" }) }); if (!audioResponse.ok) { const data: any = await audioResponse.json().catch(() => ({})); throw new Error(data.details || data.error || "Voice generation failed"); }
      audioUrl = URL.createObjectURL(await audioResponse.blob()); const audio = new Audio(audioUrl); audio.preload = "auto"; await new Promise<void>((resolve, reject) => { audio.onloadedmetadata = () => resolve(); audio.onerror = () => reject(new Error("Generated voice could not be decoded by this browser.")); });
      const canvas = canvasRef.current; if (!canvas) throw new Error("Canvas is unavailable."); canvas.width = device.width; canvas.height = device.height; const ctx = canvas.getContext("2d", { alpha: false }); if (!ctx) throw new Error("Canvas rendering context is unavailable.");
      const images = await Promise.all(storyboard.scenes.map((scene) => loadImage(scene.imageUrl as string))); const logo = branding !== "none" ? await loadImage(LOGOS[branding]) : null; const canvasStream = canvas.captureStream(device.fps);
      let audioStream: MediaStream; const capture = (audio as HTMLAudioElement & { captureStream?: () => MediaStream }).captureStream; if (capture) audioStream = capture.call(audio); else { audioContext = new AudioContext(); const source = audioContext.createMediaElementSource(audio); const destination = audioContext.createMediaStreamDestination(); source.connect(destination); source.connect(audioContext.destination); audioStream = destination.stream; }
      const combined = new MediaStream([...canvasStream.getVideoTracks(), ...audioStream.getAudioTracks()]); const recorder = new MediaRecorder(combined, { mimeType: device.mp4, videoBitsPerSecond: device.videoBitrate, audioBitsPerSecond: 128000 }); const chunks: Blob[] = []; recorder.ondataavailable = (event) => { if (event.data.size) chunks.push(event.data); };
      const done = new Promise<void>((resolve, reject) => { recorder.onstop = () => resolve(); recorder.onerror = () => reject(new Error("Browser video recording failed. The device may have run out of memory or the browser may have stopped the capture.")); }); recorder.start(device.chunkMs); await audio.play();
      const starts: number[] = []; let cursor = 0; storyboard.scenes.forEach((scene) => { starts.push(cursor); cursor += scene.durationSeconds; }); const duration = Math.max(cursor, Number.isFinite(audio.duration) ? audio.duration + 0.2 : cursor); const started = performance.now(); setStatus(`Rendering ${device.width}×${device.height} Reel on ${device.kind}…`);
      const draw = () => { const elapsed = (performance.now() - started) / 1000; let index = storyboard.scenes.findIndex((_, i) => elapsed >= starts[i] && elapsed < starts[i] + storyboard.scenes[i].durationSeconds); if (index < 0) index = storyboard.scenes.length - 1; const scene = storyboard.scenes[index]; const progress = Math.max(0, Math.min(1, (elapsed - starts[index]) / scene.durationSeconds)); ctx.fillStyle = "#111"; ctx.fillRect(0, 0, device.width, device.height); drawCover(ctx, images[index], device.width, device.height, progress); const gradient = ctx.createLinearGradient(0, device.height * 0.48, 0, device.height); gradient.addColorStop(0, "rgba(0,0,0,0)"); gradient.addColorStop(.48, "rgba(0,0,0,.18)"); gradient.addColorStop(1, "rgba(0,0,0,.88)"); ctx.fillStyle = gradient; ctx.fillRect(0, 0, device.width, device.height); if (logo) drawBrandMark(ctx, logo, device.width); ctx.fillStyle = "rgba(255,255,255,.82)"; ctx.font = `700 ${Math.round(device.width * .024)}px system-ui, sans-serif`; ctx.fillText(`${index + 1}/5`, Math.round(device.width * .045), Math.round(device.height * .044)); ctx.font = `700 ${Math.round(device.width * .05)}px system-ui, sans-serif`; const lines = wrapText(ctx, scene.caption, device.width - Math.round(device.width * .09)); const lineHeight = Math.round(device.width * .065); const boxH = lines.length * lineHeight + Math.round(device.width * .055); const boxY = device.height - boxH - Math.round(device.height * .037); ctx.fillStyle = "rgba(0,0,0,.34)"; ctx.beginPath(); ctx.roundRect(Math.round(device.width * .033), boxY - 12, device.width - Math.round(device.width * .066), boxH, 18); ctx.fill(); ctx.fillStyle = "#fff"; lines.forEach((line, lineIndex) => ctx.fillText(line, Math.round(device.width * .059), boxY + Math.round(device.width * .042) + lineIndex * lineHeight)); if (elapsed < duration) requestAnimationFrame(draw); else { audio.pause(); recorder.stop(); combined.getTracks().forEach((track) => track.stop()); } }; requestAnimationFrame(draw); await done;
      const output = new Blob(chunks, { type: device.mp4 }); if (output.size < 1000) throw new Error("Browser produced an empty or invalid video file."); const url = URL.createObjectURL(output); setVideoUrl(url); setVideoMime(device.mp4); setStatus(`Render complete · ${Math.round(duration)}s · MP4 · ${device.kind} profile.`);
    } catch (e) { setError(e instanceof Error ? e.message : String(e)); } finally { if (audioContext) await audioContext.close().catch(() => undefined); if (audioUrl) URL.revokeObjectURL(audioUrl); setBusy(null); }
  }

  async function saveReelToR2() { if (!videoUrl || !videoMime.startsWith("video/mp4")) { setError("R2 save requires an MP4 output."); return; } setBusy("save"); setError(""); setStatus("Uploading browser MP4 to R2…"); try { const blob = await fetch(videoUrl).then((r) => r.blob()); if (blob.size < 1000) throw new Error("Rendered video is empty."); const form = new FormData(); form.set("pageName", branding === "none" ? "Standalone" : branding); form.set("file", new File([blob], "reel.mp4", { type: "video/mp4" })); const response = await fetch("/api/reel-lab/assets", { method: "POST", body: form }); const data: any = await response.json(); if (!response.ok || !data.videoUrl) throw new Error(data.details || data.error || "Could not save Reel to R2."); setSavedVideoUrl(data.videoUrl); setStatus("MP4 saved to R2 successfully. Ready for download."); } catch (e) { setError(e instanceof Error ? e.message : String(e)); } finally { setBusy(null); } }

  return <main className="reel-lab-shell"><header className="reel-lab-header"><button className="reel-lab-back" onClick={() => { window.location.href = "/"; }}><ArrowLeft size={17} /> Studio</button><div><div className="reel-lab-kicker"><FilmStrip size={14} /> REEL LAB · ISOLATED TEST</div><h1>Build and render one excellent Reel.</h1><p>Standalone prompt or source post → storyboard → visuals → browser MP4 → R2.</p></div><div className="reel-lab-badge">LAB V2</div></header>
    <section className="reel-lab-grid"><div className="reel-lab-panel"><div className="reel-lab-section"><span>01</span><div><strong>Creative source</strong><small>Standalone by default · no brand assets required</small></div></div><label>Source<select value={sourceMode} onChange={(e) => setSourceMode(e.target.value as "prompt" | "post")}><option value="prompt">Standalone Reel Prompt</option><option value="post">From Source Post</option></select></label>{sourceMode === "prompt" ? <label>Reel prompt<textarea value={prompt} onChange={(e) => setPrompt(e.target.value)} rows={5} placeholder="What should this Reel explain?" /></label> : <label>Source post<textarea value={sourcePost} onChange={(e) => setSourcePost(e.target.value)} rows={7} placeholder="Paste an existing post/caption here…" /></label>}<label>Language<select value={language} onChange={(e) => setLanguage(e.target.value)}><option>Hinglish</option><option>Hindi</option><option>English</option><option>Bengali</option><option>Tamil</option><option>Telugu</option><option>Kannada</option><option>Malayalam</option><option>Marathi</option><option>Gujarati</option><option>Punjabi</option><option>Odia</option></select></label><label>Branding<select value={branding} onChange={(e) => setBranding(e.target.value as Branding)}><option value="none">None — standalone</option><option value="Zawaago">Zawaago</option><option value="InnoTech">InnoTech</option></select></label><button className="reel-lab-primary" disabled={!!busy} onClick={createStoryboard}><Sparkle size={17} /> {busy === "storyboard" ? "Creating…" : "Create Reel Storyboard"}</button><div className="render-checks"><div><CheckCircle size={16} /> {device.kind} detected</div><div>{device.mp4 ? <CheckCircle size={16} /> : <WarningCircle size={16} />} {device.mp4 ? `MP4 supported · ${device.width}×${device.height}` : "MP4 not supported"}</div><small>{device.note}</small></div></div>
      <div className="reel-lab-panel"><div className="reel-lab-section"><span>02</span><div><strong>Storyboard + assets</strong><small>Five scenes · visuals contain no forced logo/text</small></div></div>{storyboard ? <><div className="reel-topic"><strong>{storyboard.title}</strong><span>{Math.round(total)} sec · {storyboard.scenes.length} scenes</span></div><div className="scene-list">{storyboard.scenes.map((scene) => <article className="scene-card" key={scene.scene}><div className="scene-number">{scene.scene}</div><div><strong>{scene.caption}</strong><p>{scene.narration}</p>{scene.imageUrl && <img src={scene.imageUrl} alt={`Scene ${scene.scene}`} /></div></article>)}</div><button className="reel-lab-secondary" disabled={!!busy} onClick={generateSceneAssets}><Sparkle size={17} /> {busy === "assets" ? "Generating visuals…" : "Generate 5 Scene Visuals"}</button></> : <div className="reel-empty"><FilmStrip size={30} /><p>Create a storyboard to begin.</p></div>}</div>
      <div className="reel-lab-panel"><div className="reel-lab-section"><span>03</span><div><strong>Browser render</strong><small>Adaptive device profile · MP4 required for R2</small></div></div><button className="reel-lab-primary" disabled={!canRender || !!busy || !device.mp4} onClick={renderReel}><Play size={17} /> {busy === "render" ? "Rendering…" : "Render Reel MP4"}</button>{status && <div className="reel-lab-status"><SpeakerHigh size={16} /> {status}</div>}{error && <div className="reel-lab-status error"><WarningCircle size={16} /> {error}</div>}<canvas ref={canvasRef} className="reel-hidden-canvas" aria-hidden="true" />{videoUrl && <div className="video-result"><video controls playsInline src={videoUrl} /><div className="reel-actions"><a className="reel-lab-secondary" href={videoUrl} download={`reel-${branding === "none" ? "standalone" : branding.toLowerCase()}.mp4`}>Download MP4</a><button className="reel-lab-primary" disabled={!!busy} onClick={saveReelToR2}>{busy === "save" ? "Saving…" : "Save MP4 to R2"}</button></div></div>}{savedVideoUrl && <div className="reel-lab-status"><CheckCircle size={16} /> Saved to R2 · <a href={savedVideoUrl} target="_blank" rel="noreferrer">Open saved Reel</a></div>}</div></section>
    <footer className="reel-lab-footer"><strong>Isolated Reel Lab v2</strong> · Main Post/Reel production flow is untouched. This lab is the testbed for the future renderer.</footer></main>;
}
