import { Hono } from "hono";
import { createRequestHandler } from "react-router";
import { apiRoutes } from "./api";
import { galleryRoutes } from "./gallery";
import { historyRoutes } from "./history";
import { brandingRoutes } from "./branding";
import { seriesRoutes } from "./series";
import { reelLabRoutes } from "./reel-lab";
import { schedulerRoutes, processDueSchedules } from "./scheduler";
import { seriesSchedulerRoutes } from "./series-scheduler";
import { facebookHealthRoutes } from "./facebook-health";
import { reelRoutes } from "./reels";

type Env = { AI: Ai; FB_TOKEN_ZAWAAGO?: string; FB_TOKEN_INNOTECH?: string; PAGE_ID_ZAWAAGO: string; PAGE_ID_INNOTECH: string; ASSETS?: R2Bucket };
const app = new Hono<{ Bindings: Env }>();
app.route("/api", apiRoutes);
app.route("/api", galleryRoutes);
app.route("/api", historyRoutes);
app.route("/api", brandingRoutes);
app.route("/api", seriesRoutes);
app.route("/api", reelLabRoutes);
app.route("/api", schedulerRoutes);
app.route("/api", seriesSchedulerRoutes);
app.route("/api", facebookHealthRoutes);
app.route("/api", reelRoutes);
app.get("*", (c) => { const requestHandler = createRequestHandler(() => import("virtual:react-router/server-build"), import.meta.env.MODE); return requestHandler(c.req.raw, { cloudflare: { env: c.env as any, ctx: c.executionCtx as any } }); });
export default { fetch: app.fetch, async scheduled(_controller: ScheduledController, env: Env, _ctx: ExecutionContext) { await processDueSchedules(env); } };
