import { Hono } from "hono";
import { sanitizeHistoryError, writeHistory } from "./history";
import { publishFacebookReel } from "./reels";

const SCHEDULE_PREFIX = "schedules/";
type BrandName = "Zawaago" | "InnoTech";
type ScheduleStatus = "scheduled" | "processing" | "published" | "failed" | "cancelled";
type MediaType = "image" | "video";
type Env = { ASSETS?: R2Bucket; FB_TOKEN_ZAWAAGO?: string; FB_TOKEN_INNOTECH?: string; PAGE_ID_ZAWAAGO: string; PAGE_ID_INNOTECH: string };
type ScheduleRecord = { id: string; pageName: BrandName; pageId: string; caption: string; imageUrl?: string; videoUrl?: string; mediaType?: MediaType; withImage: boolean; scheduledAt: string; status: ScheduleStatus; createdAt: string; processingStartedAt?: string; publishedAt?: string; facebookPostId?: string; error?: string };

export const schedulerRoutes = new Hono<{ Bindings: Env }>();
function normalizeBrand(value: string): BrandName { const v = value.trim().toLowerCase(); if (v === "zawaago") return "Zawaago"; if (v === "innotech" || v === "inno tech") return "InnoTech"; throw new Error("Unsupported Facebook Page. Select Zawaago or InnoTech."); }
function config(page: BrandName, env: Env) { const isInno = page === "InnoTech"; const pageId = (isInno ? env.PAGE_ID_INNOTECH : env.PAGE_ID_ZAWAAGO)?.trim(); const token = (isInno ? env.FB_TOKEN_INNOTECH : env.FB_TOKEN_ZAWAAGO)?.trim(); if (!pageId) throw new Error(`Page ID is not configured for ${page}.`); if (!token) throw new Error(`Facebook Page token is not configured for ${page}.`); return { pageId, token }; }
function safeId(value: string) { if (!/^[a-zA-Z0-9-]{10,100}$/.test(value)) throw new Error("Invalid schedule id."); return value; }
function key(id: string) { return `${SCHEDULE_PREFIX}${id}.json`; }
async function save(env: Env, record: ScheduleRecord) { if (!env.ASSETS) throw new Error("Asset storage is not configured."); await env.ASSETS.put(key(record.id), JSON.stringify(record), { httpMetadata: { contentType: "application/json", cacheControl: "no-store" } }); }
async function read(env: Env, id: string) { if (!env.ASSETS) throw new Error("Asset storage is not configured."); const object = await env.ASSETS.get(key(id)); if (!object) return null; return object.json<ScheduleRecord>(); }

async function validateScheduledImage(env: Env, imageUrl: string, request?: Request) {
  if (!imageUrl.trim()) throw new Error("Image URL is required for an image schedule.");
  if (!env.ASSETS) throw new Error("Asset storage is not configured.");
  const url = new URL(imageUrl);
  if (!request) return;
  const origin = new URL(request.url).origin; const prefix = "/api/autoposter/assets/";
  if (url.origin !== origin || !url.pathname.startsWith(prefix)) throw new Error("Scheduled image must be a valid R2 asset generated by this Autoposter.");
  const encodedKey = url.pathname.slice(prefix.length); let objectKey = ""; try { objectKey = decodeURIComponent(encodedKey); } catch { throw new Error("Scheduled image URL is invalid."); }
  if (!objectKey.startsWith("generated/") || objectKey.includes("..")) throw new Error("Scheduled image must reference a generated R2 asset.");
  const object = await env.ASSETS.get(objectKey); if (!object) throw new Error("Scheduled image is no longer available in R2. Generate the visual again.");
  const contentType = object.httpMetadata?.contentType || ""; if (!contentType.toLowerCase().startsWith("image/")) throw new Error("Scheduled R2 asset is not an image."); if (object.size <= 1000) throw new Error("Scheduled image asset is unexpectedly small. Regenerate the visual.");
}

async function validateScheduledVideo(env: Env, videoUrl: string, request?: Request) {
  if (!videoUrl.trim()) throw new Error("Video URL is required for a Reel schedule.");
  if (!env.ASSETS) throw new Error("Asset storage is not configured.");
  const url = new URL(videoUrl); const prefix = "/api/autoposter/assets/";
  if (request) { const origin = new URL(request.url).origin; if (url.origin !== origin || !url.pathname.startsWith(prefix)) throw new Error("Scheduled Reel must be a valid R2 asset generated by this Autoposter."); }
  if (!url.pathname.startsWith(prefix)) throw new Error("Scheduled Reel URL is invalid.");
  const objectKey = decodeURIComponent(url.pathname.slice(prefix.length));
  if (!objectKey.startsWith("generated/") || objectKey.includes("..")) throw new Error("Scheduled Reel must reference a generated R2 asset.");
  const object = await env.ASSETS.get(objectKey); if (!object) throw new Error("Scheduled Reel is no longer available in R2.");
  const contentType = (object.httpMetadata?.contentType || "").toLowerCase(); if (contentType !== "video/mp4") throw new Error("Scheduled Reel must be an MP4 asset."); if (object.size <= 1000) throw new Error("Scheduled Reel asset is unexpectedly small.");
}

async function publish(record: ScheduleRecord, env: Env) { const { pageId, token } = config(record.pageName, env); const endpoint = record.withImage ? `https://graph.facebook.com/v20.0/${pageId}/photos` : `https://graph.facebook.com/v20.0/${pageId}/feed`; const body = new URLSearchParams({ access_token: token, message: record.caption }); if (record.withImage) { if (!record.imageUrl) throw new Error("Scheduled image post has no image URL."); body.set("url", record.imageUrl); } const response = await fetch(endpoint, { method: "POST", headers: { "content-type": "application/x-www-form-urlencoded" }, body }); const data: any = await response.json().catch(() => ({})); if (!response.ok || data.error) throw new Error(data?.error?.message || `Facebook returned HTTP ${response.status}.`); return String(data.id || data.post_id || ""); }

schedulerRoutes.post("/autoposter/schedules", async (c) => { try { const body = await c.req.json().catch(() => ({})); const pageName = normalizeBrand(String(body.page || body.pageName || "Zawaago")); const caption = String(body.caption || "").trim(); const imageUrl = String(body.imageUrl || "").trim(); const withImage = Boolean(body.withImage); const scheduledAt = String(body.scheduledAt || "").trim(); if (!caption) return c.json({ error: "Caption is required." }, 400); if (withImage) await validateScheduledImage(c.env, imageUrl, c.req.raw); const date = new Date(scheduledAt); if (!scheduledAt || Number.isNaN(date.getTime())) return c.json({ error: "A valid scheduled date/time is required." }, 400); if (date.getTime() <= Date.now() + 30_000) return c.json({ error: "Schedule time must be at least 30 seconds in the future." }, 400); const cfg = config(pageName, c.env); if (!c.env.ASSETS) return c.json({ error: "Asset storage is not configured." }, 503); const record: ScheduleRecord = { id: crypto.randomUUID(), pageName, pageId: cfg.pageId, caption, ...(imageUrl ? { imageUrl } : {}), withImage, scheduledAt: date.toISOString(), status: "scheduled", createdAt: new Date().toISOString() }; await save(c.env, record); return c.json({ ok: true, schedule: record }, 201); } catch (error) { return c.json({ error: "Schedule creation failed", details: error instanceof Error ? error.message : String(error) }, 500); } });

schedulerRoutes.post("/autoposter/schedules/reel", async (c) => { try { const body = await c.req.json().catch(() => ({})); const pageName = normalizeBrand(String(body.page || body.pageName || "Zawaago")); const caption = String(body.caption || body.description || "").trim(); const videoUrl = String(body.videoUrl || "").trim(); const title = String(body.title || "").trim().slice(0, 100); const scheduledAt = String(body.scheduledAt || "").trim(); if (!caption) return c.json({ error: "Reel caption is required." }, 400); await validateScheduledVideo(c.env, videoUrl, c.req.raw); const date = new Date(scheduledAt); if (!scheduledAt || Number.isNaN(date.getTime())) return c.json({ error: "A valid scheduled date/time is required." }, 400); if (date.getTime() <= Date.now() + 30_000) return c.json({ error: "Schedule time must be at least 30 seconds in the future." }, 400); const cfg = config(pageName, c.env); const record: ScheduleRecord = { id: crypto.randomUUID(), pageName, pageId: cfg.pageId, caption, videoUrl, mediaType: "video", withImage: false, scheduledAt: date.toISOString(), status: "scheduled", createdAt: new Date().toISOString(), ...(title ? { error: `reel-title:${title}` } : {}) }; await save(c.env, record); return c.json({ ok: true, schedule: record }, 201); } catch (error) { return c.json({ error: "Reel schedule creation failed", details: error instanceof Error ? error.message : String(error) }, 500); } });

schedulerRoutes.get("/autoposter/schedules", async (c) => { try { if (!c.env.ASSETS) return c.json({ error: "Asset storage is not configured." }, 503); const brand = c.req.query("page"); const listed = await c.env.ASSETS.list({ prefix: SCHEDULE_PREFIX, limit: 1000 }); const records: ScheduleRecord[] = []; for (const object of listed.objects) { const stored = await c.env.ASSETS.get(object.key); if (!stored) continue; try { const record = await stored.json<ScheduleRecord>(); if ((!brand || record.pageName === normalizeBrand(brand)) && record.status !== "cancelled") records.push(record); } catch { /* ignore malformed schedule objects */ } } records.sort((a, b) => a.scheduledAt.localeCompare(b.scheduledAt)); return c.json({ ok: true, schedules: records }); } catch (error) { return c.json({ error: "Could not load schedules", details: error instanceof Error ? error.message : String(error) }, 500); } });

schedulerRoutes.delete("/autoposter/schedules/:id", async (c) => { try { const id = safeId(c.req.param("id")); const record = await read(c.env, id); if (!record) return c.json({ error: "Schedule not found." }, 404); if (record.status !== "scheduled") return c.json({ error: `Schedule is already ${record.status}.` }, 409); record.status = "cancelled"; await save(c.env, record); return c.json({ ok: true, id }); } catch (error) { return c.json({ error: "Could not cancel schedule", details: error instanceof Error ? error.message : String(error) }, 500); } });

async function claimScheduledRecord(env: Env, objectKey: string, stored: R2Object, record: ScheduleRecord, now: Date) { if (!env.ASSETS) return false; const claimed: ScheduleRecord = { ...record, status: "processing", processingStartedAt: now.toISOString(), error: undefined }; const result = await env.ASSETS.put(objectKey, JSON.stringify(claimed), { onlyIf: { etagMatches: stored.httpEtag }, httpMetadata: { contentType: "application/json", cacheControl: "no-store" } }); return !!result; }
async function recoverStaleProcessing(env: Env, objectKey: string, stored: R2Object, record: ScheduleRecord, now: Date) { if (!env.ASSETS || record.status !== "processing" || !record.processingStartedAt) return false; const started = new Date(record.processingStartedAt).getTime(); if (!Number.isFinite(started) || now.getTime() - started < 10 * 60 * 1000) return false; const recovered: ScheduleRecord = { ...record, status: "scheduled", processingStartedAt: undefined, error: "Recovered stale scheduler claim." }; const result = await env.ASSETS.put(objectKey, JSON.stringify(recovered), { onlyIf: { etagMatches: stored.httpEtag }, httpMetadata: { contentType: "application/json", cacheControl: "no-store" } }); return !!result; }

export async function processDueSchedules(env: Env, now = new Date()) {
  if (!env.ASSETS) return { processed: 0, published: 0, failed: 0 };
  const listed = await env.ASSETS.list({ prefix: SCHEDULE_PREFIX, limit: 1000 }); let processed = 0, published = 0, failed = 0;
  for (const object of listed.objects) {
    const stored = await env.ASSETS.get(object.key); if (!stored) continue; let record: ScheduleRecord; try { record = await stored.json<ScheduleRecord>(); } catch { continue; }
    if (await recoverStaleProcessing(env, object.key, stored, record, now)) continue;
    if (record.status !== "scheduled" || new Date(record.scheduledAt).getTime() > now.getTime()) continue;
    const claimed = await claimScheduledRecord(env, object.key, stored, record, now); if (!claimed) continue;
    processed += 1; const processingRecord: ScheduleRecord = { ...record, status: "processing", processingStartedAt: now.toISOString(), error: undefined };
    try {
      if (processingRecord.mediaType === "video") { if (!processingRecord.videoUrl) throw new Error("Scheduled Reel has no video URL."); await validateScheduledVideo(env, processingRecord.videoUrl); const title = record.error?.startsWith("reel-title:") ? record.error.slice("reel-title:".length) : ""; const result = await publishFacebookReel(env, processingRecord.pageName, processingRecord.videoUrl, processingRecord.caption, title); const publishedAt = new Date().toISOString(); const publishedRecord: ScheduleRecord = { ...processingRecord, status: "published", processingStartedAt: undefined, publishedAt, facebookPostId: result.videoId, error: undefined }; await save(env, publishedRecord); await writeHistory(env, { id: publishedRecord.id, pageName: publishedRecord.pageName, pageId: publishedRecord.pageId, contentType: "reel", caption: publishedRecord.caption, ...(publishedRecord.videoUrl ? { imageUrl: publishedRecord.videoUrl } : {}), ...(result.videoId ? { facebookPostId: result.videoId } : {}), status: "published", createdAt: publishedAt }); published += 1; continue; }
      if (processingRecord.withImage && processingRecord.imageUrl) await validateScheduledImage(env, processingRecord.imageUrl);
      const facebookPostId = await publish(processingRecord, env);
      const publishedAt = new Date().toISOString(); const publishedRecord: ScheduleRecord = { ...processingRecord, status: "published", processingStartedAt: undefined, publishedAt, facebookPostId, error: undefined }; await save(env, publishedRecord); await writeHistory(env, { id: publishedRecord.id, pageName: publishedRecord.pageName, pageId: publishedRecord.pageId, contentType: publishedRecord.withImage ? "image" : "text", caption: publishedRecord.caption, ...(publishedRecord.imageUrl ? { imageUrl: publishedRecord.imageUrl } : {}), ...(facebookPostId ? { facebookPostId } : {}), status: "published", createdAt: publishedAt }); published += 1;
    } catch (error) {
      const message = error instanceof Error ? error.message : String(error); const failedRecord: ScheduleRecord = { ...processingRecord, status: "failed", processingStartedAt: undefined, error: sanitizeHistoryError(message) }; await save(env, failedRecord); await writeHistory(env, { id: failedRecord.id, pageName: failedRecord.pageName, pageId: failedRecord.pageId, contentType: failedRecord.mediaType === "video" ? "reel" : failedRecord.withImage ? "image" : "text", caption: failedRecord.caption, ...(failedRecord.imageUrl ? { imageUrl: failedRecord.imageUrl } : {}), status: "failed", createdAt: new Date().toISOString(), error: sanitizeHistoryError(message) }); failed += 1;
    }
  }
  return { processed, published, failed };
}
